# Generated by Django 4.1.4 on 2022-12-18 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_products_rating_products_rating_count_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
